<?php

use App\Models\Idioma;
use Illuminate\Database\Seeder;

class IdiomaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7220','descripcion'=>'DANES']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '60',  'descripcion'=>'QATO’K']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7021','descripcion'=>'ARABE']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '70',  'descripcion'=>'OLUTECO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '13',  'descripcion'=>'CORA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7231','descripcion'=>'ISLANDES']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7171','descripcion'=>'RUSO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7121','descripcion'=>'HOLANDES']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7143','descripcion'=>'ITALIANO Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '5001','descripcion'=>'ACALA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '5542','descripcion'=>'GUARANI']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7113','descripcion'=>'HINDU Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '52',  'descripcion'=>'JAKALTEKO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '28',  'descripcion'=>'PAIPAI']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '24',  'descripcion'=>'CUCAPÁ']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '5075','descripcion'=>'MANCHEÑO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '31',  'descripcion'=>'CHATINO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7141','descripcion'=>'ITALIANO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7043','descripcion'=>'CHINO Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '9999','descripcion'=>'LENGUAS E IDIOMAS NO ESPECIFICADAS']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7101','descripcion'=>'HEBREO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '36',  'descripcion'=>'IXCATECO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '68',  'descripcion'=>'AYAPANECO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7269','descripcion'=>'SWAHILI']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '26',  'descripcion'=>'KU’AHL']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7280','descripcion'=>'UZBEKO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '49',  'descripcion'=>'CHUJ']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7183','descripcion'=>'TURCO Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7051','descripcion'=>'CHINO CANTONES']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '21',  'descripcion'=>'TEPEHUANO DEL NORTE']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7209','descripcion'=>'BIELORUSO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '75',  'descripcion'=>'HUAVE']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '12',  'descripcion'=>'KICKAPOOE']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '30',  'descripcion'=>'AMUZGO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7263','descripcion'=>'SIAMES']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '65',  'descripcion'=>'TEPEHUA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7246','descripcion'=>'MAORI']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7233','descripcion'=>'KHMER']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '50',  'descripcion'=>'HUASTECO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7123','descripcion'=>'HOLANDES Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7202','descripcion'=>'ALBANES']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '78',  'descripcion'=>'TRIQUI']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7257','descripcion'=>'POLACO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7081','descripcion'=>'FRANCES']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '67',  'descripcion'=>'TARASCO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7222','descripcion'=>'ESLOVENO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '5603','descripcion'=>'OTRAS LENGUAS INDIGENAS DE AMERICA']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '55',  'descripcion'=>'LACANDÓN']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7013','descripcion'=>'ALEMAN Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '14',  'descripcion'=>'GUARIJÍO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '63',  'descripcion'=>'TSELTAL']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '59',  'descripcion'=>'Q’EQCHÍ’']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7221','descripcion'=>'ESLOVACO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7251','descripcion'=>'NEPALES']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '71',  'descripcion'=>'POPOLUCA DE LA SIERRA']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '47',  'descripcion'=>'AKATEKO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '34',  'descripcion'=>'CHOCHOLTECO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7237','descripcion'=>'LAO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7279','descripcion'=>'UCRANIANO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7259','descripcion'=>'SAMOANO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '48',  'descripcion'=>'AWAKATEKO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7214','descripcion'=>'CATALAN']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7242','descripcion'=>'MALAYO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7285','descripcion'=>'OTROS IDIOMAS EXTRANJEROS NO OFICIALES']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7073','descripcion'=>'COREANO Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '83',  'descripcion'=>'INGLÉS']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7227','descripcion'=>'GEORGIANO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7239','descripcion'=>'LETON']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7258','descripcion'=>'RUMANO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7063','descripcion'=>'CHINO MANDARIN Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7111','descripcion'=>'HINDU']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7071','descripcion'=>'COREANO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '62',  'descripcion'=>'TOJOLABAL']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '73',  'descripcion'=>'TEXISTEPEQUEÑO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7161','descripcion'=>'PORTUGUES']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7240','descripcion'=>'LITUANO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7225','descripcion'=>'FINLANDES']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7212','descripcion'=>'BULGARO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '81',  'descripcion'=>'ESPAÑOL']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '45',  'descripcion'=>'TLAPANECO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '51',  'descripcion'=>'IXIL']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7091','descripcion'=>'GRIEGO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7181','descripcion'=>'TURCO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7223','descripcion'=>'ESTONIO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '20',  'descripcion'=>'TARAHUMARA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '5551','descripcion'=>'QUECHUA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7011','descripcion'=>'ALEMAN']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '37',  'descripcion'=>'MATLATZINCA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7041','descripcion'=>'CHINO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '61',  'descripcion'=>'TEKO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7224','descripcion'=>'FILIPINO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '64',  'descripcion'=>'TSOTSIL']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '60000','descripcion'=>'LENGUAS E IDIOMAS INSUFICIENTEMENTE ESPECIFICADAS']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7211','descripcion'=>'BISLAMA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '5601','descripcion'=>'YUMA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7151','descripcion'=>'JAPONES']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7033','descripcion'=>'CHECO Y OTROS(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '18',  'descripcion'=>'PÁPAGO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7268','descripcion'=>'SUECO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '22',  'descripcion'=>'TEPEHUANO DEL SUR']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '961', 'descripcion'=>'KANJOBAL']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '69',  'descripcion'=>'MIXE']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7083','descripcion'=>'FRANCES Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7228','descripcion'=>'HUNGARO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '72',  'descripcion'=>'SAYULTECO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7173','descripcion'=>'RUSO Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '25',  'descripcion'=>'KILIWA']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '77',  'descripcion'=>'CHONTAL DE TABASCO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '44',  'descripcion'=>'TLAHUICA']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '76',  'descripcion'=>'CH´OL']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '16',  'descripcion'=>'MAYO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '941', 'descripcion'=>'MAME']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7032','descripcion'=>'ALUSION AL MANEJO DEL CHECO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7282','descripcion'=>'VIETNAMITA']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '17',  'descripcion'=>'NÁHUATL']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7216','descripcion'=>'CINGALES']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7163','descripcion'=>'PORTUGUES Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '29',  'descripcion'=>'SERI']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '15',  'descripcion'=>'HUICHOL']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7254','descripcion'=>'NORUEGO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '41',  'descripcion'=>'OTOMÍ']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7023','descripcion'=>'ARABE Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7262','descripcion'=>'SESELWA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7093','descripcion'=>'GRIEGO Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '66',  'descripcion'=>'TOTONACO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7226','descripcion'=>'FORINGIO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '43',  'descripcion'=>'POPOLOCA']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '39',  'descripcion'=>'MAZATECO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7031','descripcion'=>'CHECO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7132','descripcion'=>'ALUSION AL MANEJO DEL INGLES']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '19',  'descripcion'=>'PIMA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7248','descripcion'=>'MONGOL']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '54',  'descripcion'=>'KAQCHIKEL']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7053',  'descripcion'=>'CHINO CANTONES Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '40',  'descripcion'=>'MIXTECO']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7061','descripcion'=>'CHINO MANDARIN']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '5537','descripcion'=>'EMBERA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7256','descripcion'=>'PERSA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7122','descripcion'=>'ALUSION AL MANEJO DEL HOLANDES']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7249','descripcion'=>'NAURUANO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '57',  'descripcion'=>'MAYA']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '46',  'descripcion'=>'ZAPOTECO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '42',  'descripcion'=>'PAME']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '53',  'descripcion'=>'K’ICHE']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7133','descripcion'=>'INGLES Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '58',  'descripcion'=>'Q’ANJOB’AL']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7208','descripcion'=>'BENGALI']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7230','descripcion'=>'IRLANDES']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '35',  'descripcion'=>'CUICATECO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '27',  'descripcion'=>'KUMIAI']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '23',  'descripcion'=>'YAQUI']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7131','descripcion'=>'INGLES']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7182','descripcion'=>'ALUSION AL MANEJO DEL TURCO']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '79',  'descripcion'=>'ZOQUE']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '32',  'descripcion'=>'CHICHIMECO JONAZ']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '56',  'descripcion'=>'MAM']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '38',  'descripcion'=>'MAZAHUA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7153','descripcion'=>'JAPONES Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '74',  'descripcion'=>'CHONTAL DE OAXACA']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '7103','descripcion'=>'HEBREO Y OTRO(S) IDIOMA(S)']);
        factory(Idioma::class,1)->create(['tipo' => 'I', 'clave' => '5522','descripcion'=>'CHEYENE']);
        factory(Idioma::class,1)->create(['tipo' => 'L', 'clave' => '33',  'descripcion'=>'CHINANTECO']);
    }
}
