SET AUTOCOMMIT = 0;
START TRANSACTION;

--
-- Estructura de tabla para la tabla `temp_listado_administrativos`
--
DROP TABLE IF EXISTS `temp_listado_administrativos`;

CREATE TABLE `temp_listado_administrativos` (
                                                `id` bigint(20) NOT NULL,
                                                `unidad_responsable` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `tipo_de_plaza` char(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `puesto_generico` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `puesto_especifico` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `apellido_paterno` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `apellido_materno` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `nombre` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `sexo` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `rfc` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `curp` varchar(18) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                `correo_electronico` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `temp_listado_administrativos`
--


INSERT INTO `temp_listado_administrativos` (`id`, `unidad_responsable`, `tipo_de_plaza`, `puesto_generico`, `puesto_especifico`, `apellido_paterno`, `apellido_materno`, `nombre`, `sexo`, `rfc`, `curp`, `correo_electronico`) VALUES
(1, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA TECNICO', 'ORIENTADORA EDUCATIVA', 'ACEVEDO', 'CASTILLO', 'CHRISTIAN MARIBEL', 'M', 'AECC8601173I5', 'AECC860117MYNCSH00', 'christian.acevedo@evasamano.edu.mx'),
(2, 'DIRECCIÓN DE PLANEACIÓN', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'AGUILAR', 'KUMUL', 'MARIA JOVITA', 'M', 'AUKJ6902075H6', 'AUKJ690207MQRGMV05', 'maria.jovita@evasamano.edu.mx'),
(3, 'DIRECCIÓN DE PLANEACIÓN', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'AGUILAR', 'MENDEZ', 'ANA FELICIA', 'M', 'AUMA720930MJ4', 'AUMA720930MQRGNN04', 'ana.felicia@evasamano.edu.mx'),
(4, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'AGUILAR', 'MENDEZ', 'CARLA PATRICIA', 'M', 'AUMC710128HK4', 'AUMC710128MQRGNR08', 'carla.aguilar@evasamano.edu.mx'),
(5, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'ALBORNOZ', 'NARVAEZ', 'GLENDY GUADALUPE', 'M', 'AONG8012152A5', 'AONG801215MYNLRL07', 'glendy.albornoz@evasamano.edu.mx'),
(6, 'DESPACHO DE LA DIRECCIÓN ACADÉMICA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'ANGULO', 'GONZALEZ', 'JESSICA ARLETTE', 'M', 'AUGJ7802273W2', 'AUGJ780227MQRNNS08', 'jessica.angulo@evasamano.edu.mx'),
(7, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'OFICIAL', 'MANTENIMIENTO', 'ANGULO', 'VILLANUEVA', 'ROBERTO', 'H', 'AUVR601110IL7', 'AUVR601110HQRNLB09', 'roberto.angulo@evasamano.edu.mx'),
(8, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'ARIAS', 'ECHAZARRIETA', 'NELBA', 'M', 'AIEN750208KH8', 'AIEN750208MQRRCL04', 'financieros@evasamano.edu.mx'),
(9, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'AVILA', 'PALOMO', 'LETICIA GUADALUPE', 'M', 'AIPL6705128K8', 'AIPL670512MYNVLT02', 'leticia.avila@evasamano.edu.mx'),
(10, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'CO', 'JEFE(A) DE DEPARTAMENTO', 'COORDINADOR DE PLANTEL', 'AZUETA', 'SANCHEZ ', 'SILVIO MARIEL', 'H', 'AUSS610208PU7', 'AUSS610208HQRZNL05', 'silvio.azueta@evasamano.edu.mx'),
(11, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'CO', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'BALAM ', 'JIMENEZ  ', 'JESÚS ANTONIO', 'H', 'BAJJ810104UB1', 'BAJJ810104HQRLMS08', 'jesus.balam@evasamano.edu.mx'),
(12, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'MENSAJERO(A)', 'VIGILANTE', 'BAREA', 'ESTRELLA', 'JOSE ALBERTO', 'H', 'BAEA561115UB7', 'BAEA561115HYNRSL04', 'jose.barea@evasamano.edu.mx'),
(13, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'CO', 'DIRECTOR(A)', 'DIRECTOR DE PLANTEL', 'BLANCO', 'AGUILAR', 'GABRIEL', 'H', 'BAAG600420340', 'BAAG600420HCLLGB06', 'gabriel.blanco@evasamano.edu.mx'),
(14, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'BLANCO', 'LEYVA', 'CARLOS', 'H', 'BALC670901RB3', 'BALC670901HOCLYR01', 'BALC670901RB3@SINREGISTRAR.EDU.MX'),
(15, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'BRACAMONTE', 'CABRERA', 'ANA BERTHA', 'M', 'BACA751018SN6', 'BXCA751018MQRRBN09', 'BACA751018SN6@SINREGISTRAR.EDU.MX'),
(16, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'PREFECTO', 'BRITO', 'GONGORA', 'MANUEL ENRIQUE', 'H', 'BIGM770530GY8', 'BIGM770530HYNRNN06', 'manuel.brito@evasamano.edu.mx'),
(17, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'CAB', 'PALOMO', 'MARIA INOCENCIA DE JESUS', 'M', 'CAPI721228DZ8', 'CAPI721228MYNBLN01', 'ino.financieros@evasamano.edu.mx'),
(18, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'CALDERON', 'MARIN', 'AREOLA MARGARITA', 'M', 'CAMA740917V9A', 'CAMA740917MQRLRR06', 'areola.calderon@evasamano.edu.mx'),
(19, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'PREFECTO', 'CAMARA', 'SALAZAR', 'JOSE MARTIN', 'H', 'CASM630319GU5', 'CASM630319HYNMLR06', 'jose.camara@evasamano.edu.mx'),
(20, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'PREFECTO', 'CAMELO', 'MENDEZ', 'KARINA SERAFINA', 'M', 'CAMK7605187V9', 'CAMK760518MYNMNR04', 'karina.camelo@evasamano.edu.mx'),
(21, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'PREFECTO', 'CANCHE', 'MENDEZ', 'EDGAR ESTEBAN', 'H', 'CAME721128BV2', 'CAME721128HYNNND08', 'edgar.canche@evasamano.edu.mx'),
(22, 'DIRECCIÓN JURÍDICA Y UNIDAD DE TRANSPARENCIA Y ACCESO A LA INFORMACIÓN PUBLICA Y PROTECCIÓN DE DATOS PERSONALES ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'CANTO', 'FLORES', 'ELSY MARIA', 'M', 'CAFE710228I26', 'CAFE710228MQRNLL04', 'elsy.canto@evasamano.edu.mx'),
(23, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'PREFECTO', 'CANTO', 'MONTALVO', 'LEYDI', 'M', 'CAML7708277DA', 'CAML770827MQRNNY02', 'leydi.canto@evasamano.edu.mx'),
(24, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'CARDEÑA', 'SOSA', 'CRISTINA LUCENDY', 'M', 'CASC761026CH9', 'CASC761026MQRRSR05', 'cristina.cardena@evasamano.edu.mx'),
(25, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'CARRASCO', 'SAMOS', 'ROSARIO DEL CARMEN', 'M', 'CASR6311184U1', 'CASR631118MQRRMS04', 'rosario.carrasco@evasamano.edu.mx'),
(26, 'DESPACHO DE LA DIRECCIÓN ACADÉMICA', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'CASTILLO', 'CANUL', 'ADALBERTA', 'M', 'CACX680423117', 'CXCA680423MYNSND00', 'adycastillo@evasamano.edu.mx'),
(27, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'CASTILLO', 'PEREZ', 'MIGUEL ANGEL', 'H', 'CAPM551126BI7', 'CAPM551126HQRSRG08', 'miguel.castillo@evasamano.edu.mx'),
(28, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'CETINA', 'RODRIGUEZ', 'LOURDES MARIA ASUNCION', 'M', 'CERL7608155M4', 'CERL760815MQRTDR05', 'lourdes.cetina@evasamano.edu.mx'),
(29, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'CHAN', 'CHIQUIL', 'MIRNA LETICIA', 'M', 'CACM740210C99', 'CACM740210MQRHHR00', 'leticia.chan@evasamano.edu.mx'),
(30, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'CHAN', 'TUT', 'CLARA DE JESUS', 'M', 'CATC750314GQ9', 'CATC750314MQRHTL01', 'rec.humanos@evasamano.edu.mx'),
(31, 'DESPACHO DE LA DIRECCIÓN GENERAL', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'CHE', 'PERERA', 'JOSE ANGEL', 'H', 'CEPA850727SU5', 'CEPA850727HQRHRN04', 'jose.che@evasamano.edu.mx'),
(32, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'CHUC', 'BERMON', 'IMELDA', 'M', 'CUBI780716PZ0', 'CUBI780716MYNHRM06', 'imelda.chuc@evasamano.edu.mx'),
(33, 'DESPACHO DE LA DIRECCIÓN GENERAL', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'CORDOVA', 'CHAN', 'ROSA ELENA', 'M', 'COCR750402E94', 'COCR750402MCCRHS05', 'COCR750402E94@SINREGISTRAR.EDU.MX'),
(34, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'MENSAJERO(A)', 'VIGILANTE', 'CRUZ', 'MERCADO', 'NOE', 'H', 'CUMN720204QV2', 'CUMN720204HVZRRX08', 'noe.cruz@evasamano.edu.mx'),
(35, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'CRUZ', 'PEREZ', 'TILA DEL CARMEN', 'M', 'CUPT730614I67', 'CUPT730614MCCRRL05', 'tcruzperez@evasamano.edu.mx'),
(36, 'DESPACHO DE LA DIRECCIÓN ACADÉMICA', 'CO', 'DIRECTOR(A) DE AREA A', 'DIRECTORA ACADÉMICA', 'DIAZ', 'VELASCO', 'IRANI CORAZU', 'M', 'DIVI870116A60', 'DIVI870116MQRZLR09', 'irani.diaz@evasamano.edu.mx'),
(37, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'PREFECTO', 'DOMINGUEZ', 'GARCIA', 'AZUCENA', 'M', 'DOGA780721CW4', 'DOGA780721MCCMRZ13', 'azucena.dominguez@evasamano.edu.mx'),
(38, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'DUARTE', 'OROZCO', 'NORMA MARIA', 'M', 'DUON860908QA0', 'DUON860908MQRRRR04', 'norma.duarte@evasamano.edu.mx'),
(39, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'ESPINO', 'GARCIA', 'DAMIAN', 'H', 'EIGD741009U51', 'EIGD741009HQRSRM02', 'damian@evasamano.edu.mx'),
(40, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'FUENTES', 'FERNANDEZ', 'TERESA DE JESUS', 'M', 'FUFT701202493', 'FUFT701202MQRNRR09', 'teresa.fuentes@evasamano.edu.mx'),
(41, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'GARCIA', 'ESQUILIANO', 'ALBERTO SUSANO', 'H', 'GAEA6808116D2', 'GAEA680811HQRRSL01', 'alberto.garcia@evasamano.edu.mx'),
(42, 'DESPACHO DE LA DIRECCIÓN GENERAL', 'CO', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'GARCIA', 'LOPEZ', 'ANGEL ABRAHAM', 'H', 'GALA881216K93', 'GALA881216HQRRPN06', 'abraham.garcia@evasamano.edu.mx'),
(43, 'DESPACHO DE LA DIRECCIÓN ACADÉMICA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'GONGORA', 'SUTHERLAND', 'AURORA ESMERALDA', 'M', 'GOSA860509V79', 'GOSA860509MQRNTR05', 'aurora.gongora@evasamano.edu.mx'),
(44, 'DESPACHO DE LA DIRECCIÓN ACADÉMICA', 'CO', 'JEFE(A) DE DEPARTAMENTO ', 'JEFA DE DEPARTAMENTO DE SERVICIOS ESCOLARES', 'GONZALEZ', 'MAYO', 'MURIEL ABEL', 'H', 'GOMM811205DQ6', 'GOMM811205HQRNYR09', 'muriel.gonzalez@evasamano.edu.mx'),
(45, 'DIRECCIÓN DE PLANEACIÓN', 'CO', 'JEFE(A) DE DEPARTAMENTO ', 'JEFE DE DEPARTAMENTO DE PROGRAMACIÓN Y PRESUPUESTO', 'GONZALEZ ', 'HERNANDEZ', 'ALFREDO', 'H', 'GOHA850719264', 'GOHA850719HQRNRL07', 'alfredo.glezhdz@evasamano.edu.mx'),
(46, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'GUTIERREZ', 'GOMEZ', 'CLAUDIA DE ASIS', 'M', 'GUGC810811E60', 'GUGC810811MQRTML03', 'claudia.gutierrez@evasamano.edu.mx'),
(47, 'DIRECCIÓN DE PLANEACIÓN', 'CO', 'JEFE(A) DE DEPARTAMENTO', 'JEFA DE DEPARTAMENTO DE PROCESOS ADMINISTRATIVOS, VINCULACIÓN Y ESTADÍSTICA', 'GUTIERREZ', 'GOMEZ', 'EMILSE ANDREA', 'M', 'GUGE870321KJ1', 'GUGE870321MQRTMM07', 'emilse.gutierrez@evasamano.edu.mx'),
(48, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'INTENDENTE', 'INTENDENTE', 'HERNANDEZ', 'ROSALES', 'JUAN ANTONIO', 'H', 'HERJ5704073FA', 'HERJ570407HCCRSN16', 'juan.hernandez@evasamano.edu.mx'),
(49, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'KAN', 'CANCHE', 'BLANCA ARACELI', 'M', 'KACB790330916', 'KACB790330MQRNNL02', 'blanca.kan@evasamano.edu.mx'),
(50, 'DESPACHO DE LA DIRECCIÓN ACADÉMICA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'LOPEZ', 'CASTILLO', 'ABRIL YOLISMA', 'M', 'LOCA811218R41', 'LXCA811218MQRPSB09', 'abril.lopez@evasamano.edu.mx'),
(51, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'CO', 'DIRECTOR(A) DE AREA A', 'DIRECTORA ADMINISTRATIVA', 'LOPEZ', 'CHAN', 'INES', 'M', 'LOCI570210H53', 'LOCI570210MCCPHN03', 'dir.administrativa@evasamano.edu.mx'),
(52, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'MARIN', 'UC', 'JIMMY ENRIQUE', 'H', 'MAUJ91050765A', 'MAUJ910507HYNRCM03', 'jimmy.marin@evasamano.edu.mx'),
(53, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'MARTINEZ', 'PEREZ', 'REYNA GUADALUPE', 'M', 'MAPR760204UUA', 'MAPR760204MYNRRY08', 'reyna.martinez@evasamano.edu.mx'),
(54, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'MAY', 'GONGORA', 'SERGIO DANIEL', 'H', 'MAGS6811128U9', 'MAGS681112HYNYNR04', 'sergio.may@evasamano.edu.mx'),
(55, 'DESPACHO DE LA DIRECCIÓN ACADÉMICA', 'CO', 'JEFE(A) DE DEPARTAMENTO', 'JEFE DE DEPARTAMENTO DE DESARROLLO Y EXTENSIÓN ACADEMICA', 'MEDINA', 'PEREZ', 'SERGIO SALVADOR', 'H', 'MEPS690106QN7', 'MEPS690106HCCDRR06', 'MEPS690106QN7@SINREGISTRAR.EDU.MX'),
(56, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'PREFECTO', 'MEDRANO', 'RIVERA', 'ADA CILIA', 'M', 'MERA740628L45', 'MERA740628MQRDVD05', 'ada.medrano@evasamano.edu.mx'),
(57, 'DIRECCIÓN DE PLANEACIÓN', 'CO', 'DIRECTOR(A) DE AREA A', 'DIRECTORA DE PLANEACIÓN', 'MONTIEL', 'AVILA', 'MIRIAM', 'M', 'MOAM740307BY6', 'MOAM740307MMCNVR04', 'miriam.montiel@evasamano.edu.mx'),
(58, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'INTENDENTE', 'INTENDENTE', 'MOO', 'CHAN', 'DEMETRIO', 'H', 'MOCD600409N38', 'MOCD600409HQRXHM06', 'demetrio.moo@evasamano.edu.mx'),
(59, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'MORALES', 'GONZALEZ', 'ELVIA BENITA CONCEPCION', 'M', 'MOGE751208UR5', 'MOGE751208MQRRNL22', 'elvia.morales@evasamano.edu.mx'),
(60, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'NAVARRETE', 'CHE', 'LOURDES ALEJANDRA', 'M', 'NACL770314IW6', 'NACL770314MQRVHR06', 'alejandra.navarrete@evasamano.edu.mx'),
(61, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'NAVARRETE', NULL, 'NIDIA MARGARITA', 'M', 'NANI6804147X7', 'NAXN680414MYNVXD05', 'nidia.navarrete@evasamano.edu.mx'),
(62, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'ONOFRE', 'VALLE', 'ISLA DEL ROCIO', 'M', 'OOVI6510187F7', 'OOVI651018MQRNLS01', 'rocio.onofre@evasamano.edu.mx'),
(63, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'CO', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'ONOFRE ', 'AVILA ', 'ZULEYMA GUADALUPE', 'M', 'OOAZ901216AHA', 'OOAZ901216MOCNVL02', 'zuleyma.onofre@evasamano.edu.mx'),
(64, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'PACHECO', 'COLLI', 'CLAUDIA PAMELA', 'M', 'PACC8507079A7', 'PACC850707MQRCLL03', 'pamela.pacheco@evasamano.edu.mx'),
(65, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'PECH', 'PALACIO', 'BEATRIZ EUGENIA', 'M', 'PEPB740527C18', 'PEPB740527MCCCLT09', 'beatrizpech@evasamano.edu.mx'),
(66, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'INTENDENTE', 'INTENDENTE', 'PEÑA', 'BARCENAS', 'CARLOS', 'H', 'PEBC530623JL6', 'PEBC530623HMNXRR02', 'PEBC530623JL6@SINREGISTRAR.EDU.MX'),
(67, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'PEREZ', 'SANTIAGO', 'ELIZABETH', 'M', 'PESE780127BZ2', 'PESE780127MQRRNL06', 'elizabeth.perez@evasamano.edu.mx'),
(68, 'DESPACHO DE LA DIRECCIÓN GENERAL', 'CO', 'TITULAR DE UNIDAD', 'TITULAR DE UNIDAD DE SERVICIOS INFORMÁTICOS.', 'RAMIREZ', 'ORTIZ', 'MAGDALENA DEL ROSARIO', 'M', 'RAOM800911K46', 'RAOM800911MQRMRG03', 'magdalena.ramirez@evasamano.edu.mx'),
(69, 'DIRECCIÓN JURÍDICA Y UNIDAD DE TRANSPARENCIA Y ACCESO A LA INFORMACIÓN PUBLICA Y PROTECCIÓN DE DATOS PERSONALES ', 'CO', 'DIRECTOR(A) DE AREA A', 'DIRECTOR JURÍDICO Y UNIDAD DE TRANSPARENCIA Y ACCESO A LA INFORMACIÓN PUBLICA Y PROTECCIÓN DE DATOS PERSONALES ', 'SABIDO', 'ALCOCER', 'VICTOR AARON', 'H', 'SAAV750802TF4', 'SAAV750802HQRBLC01', 'juridico@evasamano.edu.mx'),
(70, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'SANCHEZ', 'CASTILLO', 'JUAN JOSE', 'H', 'SACJ8104209VA', 'SACJ810420HDFNSN05', 'juan.sanchez@evasamano.edu.mx'),
(71, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'JEFE(A) DE OFICINA', 'RESPONSABLE DE ÁREA', 'SANCHEZ', 'MORALES', 'SONIA', 'M', 'SAMS750606996', 'SAMS750606MVZNRN06', 'sonia.sanchez@evasamano.edu.mx'),
(72, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'SCHULTZ', 'CHELUJA', 'IVAN DAVID', 'H', 'SUCI770102TC1', 'SUCI770102HQRCHV04', 'ivan.schultz@evasamano.edu.mx'),
(73, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'CO', 'JEFE(A) DE DEPARTAMENTO ', 'JEFE DE DEPARTAMENTO DE RECURSOS HUMANOS Y FINANCIEROS', 'TORRES', 'ESTAÑOL', 'RUBEN MAURICIO', 'H', 'TOER870731562', 'TOER870731HQRRSB00', 'ruben.torres@evasamano.edu.mx'),
(74, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'INTENDENTE', 'INTENDENTE', 'TORREZ', 'REYES', 'ISMAEL', 'H', 'TORI671124365', 'TORI671124HCSRYS02', 'ismael.torrez@evasamano.edu.mx'),
(75, 'DESPACHO DE LA DIRECCIÓN ACADÉMICA', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'TUN', 'XIX', 'DAVID REYES', 'H', 'TUXD840523HM1', 'TUXD840523HQRNXV08', 'davidtun@evasamano.edu.mx'),
(76, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA TECNICO', 'ORIENTADORA EDUCATIVA', 'UC', 'AYALA', 'MONICA NOELIA', 'M', 'UAMO810918PB1', 'UXAM810918MYNCYN00', 'monica.uc@evasamano.edu.mx'),
(77, 'DESPACHO DE LA DIRECCIÓN GENERAL', 'CO', 'DIRECTOR(A) GENERAL DE ORGANISMO B', 'DIRECTOR GENERAL', 'UC', 'SOSA', 'CARLOS MARIO', 'H', 'USCA700206SX6', 'UXSC700206HCCCSR04', 'carlosmariouc@evasamano.edu.mx'),
(78, 'DESPACHO DE LA DIRECCIÓN ADMINISTRATIVA', 'CO', 'JEFE(A) DE DEPARTAMENTO ', 'JEFE DE DEPARTAMENTO RECURSOS MATERIALES Y SERVICIOS GENERALES', 'VALDEZ', 'GONZALEZ', 'LUIS FELIPE DE SAN MARTIN DE PORRES', 'H', 'VAGL640905KQ3', 'VAGL640905HQRLNS06', 'luis.valdez@evasamano.edu.mx'),
(79, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA  PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'VARGAS', 'PEREZ', 'LUIS MARIO', 'H', 'VAPL790710759', 'VAPL790710HQRRRS09', 'mario.vargas@evasamano.edu.mx'),
(80, 'DESPACHO DE LA DIRECCIÓN ACADÉMICA', 'BA', 'ANALISTA  PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVO', 'XIX', 'EUAN', 'MARTIN', 'H', 'XIEM611111TU8', 'XIEM611111HYNXNR04', 'martinxix@evasamano.edu.mx'),
(81, 'DIRECCIÓN PLANTEL EVA SÁMANO ', 'BA', 'ANALISTA PROFESIONAL', 'AUXILIAR TÉCNICO ADMINISTRATIVA', 'ZAPATA', 'CHIM', 'ERIKA YOLANDA', 'M', 'ZACE780615Q8A', 'ZACE780615MYNPHR06', 'erika.zapata@evasamano.edu.mx');




--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `temp_listado_administrativos`
--
ALTER TABLE `temp_listado_administrativos`
    ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `temp_listado_administrativos`
--
ALTER TABLE `temp_listado_administrativos`
    MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=82;

COMMIT;
SET AUTOCOMMIT = 1;
